version: '3.8'

services:
  osrm:
    build:
      context: ./osrm
    volumes:
      - ./osrm:/osrm
    ports:
      - "4200:5000"

  engine:
    build: ./engine
    ports:
      - "4210:8080"
    depends_on:
      - osrm
    environment:
      - OSRM_BASE_URL=http://osrm:5000
      - DEBUG_SKIP_DROP_PENALTY=false
      - DEBUG_SKIP_DISTANCE_DIMENSION=true
      - DEBUG_SKIP_TIME_DIMENSION=true
      - DEBUG_SKIP_SEAT_CAPACITY=true
      - DEBUG_SKIP_WHEELCHAIR_CAPACITY=true
      - DEBUG_SKIP_PICKUP_DELIVERY=true
      - DEBUG_SKIP_MAX_RIDE_TIME=true
      - DEBUG_SKIP_VEHICLE_TIME_CONSTRAINTS=true
      - DEBUG_SKIP_COMPATIBILITY=true
      - DEBUG_SKIP_REST_CONSTRAINTS=true
